// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: proto/aoc.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SolveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Year  int32  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Day   int32  `protobuf:"varint,2,opt,name=day,proto3" json:"day,omitempty"`
	Part2 bool   `protobuf:"varint,3,opt,name=part2,proto3" json:"part2,omitempty"`
	Input string `protobuf:"bytes,4,opt,name=input,proto3" json:"input,omitempty"`
}

func (x *SolveRequest) Reset() {
	*x = SolveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_aoc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SolveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolveRequest) ProtoMessage() {}

func (x *SolveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aoc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolveRequest.ProtoReflect.Descriptor instead.
func (*SolveRequest) Descriptor() ([]byte, []int) {
	return file_proto_aoc_proto_rawDescGZIP(), []int{0}
}

func (x *SolveRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *SolveRequest) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *SolveRequest) GetPart2() bool {
	if x != nil {
		return x.Part2
	}
	return false
}

func (x *SolveRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

type SolveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *SolveResponse) Reset() {
	*x = SolveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_aoc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SolveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolveResponse) ProtoMessage() {}

func (x *SolveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aoc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolveResponse.ProtoReflect.Descriptor instead.
func (*SolveResponse) Descriptor() ([]byte, []int) {
	return file_proto_aoc_proto_rawDescGZIP(), []int{1}
}

func (x *SolveResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_proto_aoc_proto protoreflect.FileDescriptor

var file_proto_aoc_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x6f, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x03, 0x61, 0x6f, 0x63, 0x22, 0x60, 0x0a, 0x0c, 0x53, 0x6f, 0x6c, 0x76, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x79, 0x65, 0x61, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x61,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x64, 0x61, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x61, 0x72, 0x74, 0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x70, 0x61, 0x72,
	0x74, 0x32, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x22, 0x27, 0x0a, 0x0d, 0x53, 0x6f, 0x6c, 0x76,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x32, 0x3b, 0x0a, 0x09, 0x41, 0x4f, 0x43, 0x53, 0x6f, 0x6c, 0x76, 0x65, 0x72, 0x12, 0x2e,
	0x0a, 0x05, 0x53, 0x6f, 0x6c, 0x76, 0x65, 0x12, 0x11, 0x2e, 0x61, 0x6f, 0x63, 0x2e, 0x53, 0x6f,
	0x6c, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x61, 0x6f, 0x63,
	0x2e, 0x53, 0x6f, 0x6c, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x11,
	0x5a, 0x0f, 0x61, 0x6f, 0x63, 0x2d, 0x69, 0x6e, 0x2d, 0x67, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_aoc_proto_rawDescOnce sync.Once
	file_proto_aoc_proto_rawDescData = file_proto_aoc_proto_rawDesc
)

func file_proto_aoc_proto_rawDescGZIP() []byte {
	file_proto_aoc_proto_rawDescOnce.Do(func() {
		file_proto_aoc_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_aoc_proto_rawDescData)
	})
	return file_proto_aoc_proto_rawDescData
}

var file_proto_aoc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_aoc_proto_goTypes = []interface{}{
	(*SolveRequest)(nil),  // 0: aoc.SolveRequest
	(*SolveResponse)(nil), // 1: aoc.SolveResponse
}
var file_proto_aoc_proto_depIdxs = []int32{
	0, // 0: aoc.AOCSolver.Solve:input_type -> aoc.SolveRequest
	1, // 1: aoc.AOCSolver.Solve:output_type -> aoc.SolveResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_aoc_proto_init() }
func file_proto_aoc_proto_init() {
	if File_proto_aoc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_aoc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SolveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_aoc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SolveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_aoc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_aoc_proto_goTypes,
		DependencyIndexes: file_proto_aoc_proto_depIdxs,
		MessageInfos:      file_proto_aoc_proto_msgTypes,
	}.Build()
	File_proto_aoc_proto = out.File
	file_proto_aoc_proto_rawDesc = nil
	file_proto_aoc_proto_goTypes = nil
	file_proto_aoc_proto_depIdxs = nil
}
