// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: proto/aoc.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AOCSolverClient is the client API for AOCSolver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AOCSolverClient interface {
	Solve(ctx context.Context, in *SolveRequest, opts ...grpc.CallOption) (*SolveResponse, error)
}

type aOCSolverClient struct {
	cc grpc.ClientConnInterface
}

func NewAOCSolverClient(cc grpc.ClientConnInterface) AOCSolverClient {
	return &aOCSolverClient{cc}
}

func (c *aOCSolverClient) Solve(ctx context.Context, in *SolveRequest, opts ...grpc.CallOption) (*SolveResponse, error) {
	out := new(SolveResponse)
	err := c.cc.Invoke(ctx, "/aoc.AOCSolver/Solve", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AOCSolverServer is the server API for AOCSolver service.
// All implementations must embed UnimplementedAOCSolverServer
// for forward compatibility
type AOCSolverServer interface {
	Solve(context.Context, *SolveRequest) (*SolveResponse, error)
	mustEmbedUnimplementedAOCSolverServer()
}

// UnimplementedAOCSolverServer must be embedded to have forward compatible implementations.
type UnimplementedAOCSolverServer struct {
}

func (UnimplementedAOCSolverServer) Solve(context.Context, *SolveRequest) (*SolveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Solve not implemented")
}
func (UnimplementedAOCSolverServer) mustEmbedUnimplementedAOCSolverServer() {}

// UnsafeAOCSolverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AOCSolverServer will
// result in compilation errors.
type UnsafeAOCSolverServer interface {
	mustEmbedUnimplementedAOCSolverServer()
}

func RegisterAOCSolverServer(s grpc.ServiceRegistrar, srv AOCSolverServer) {
	s.RegisterService(&AOCSolver_ServiceDesc, srv)
}

func _AOCSolver_Solve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SolveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AOCSolverServer).Solve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aoc.AOCSolver/Solve",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AOCSolverServer).Solve(ctx, req.(*SolveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AOCSolver_ServiceDesc is the grpc.ServiceDesc for AOCSolver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AOCSolver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aoc.AOCSolver",
	HandlerType: (*AOCSolverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Solve",
			Handler:    _AOCSolver_Solve_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/aoc.proto",
}
